from enum import Enum


class ReviewStatus(str, Enum):
    INITIATED = "INITIATED"
    WAITING_FORM = "WAITING_FORM"
    FORM_SUBMITTED = "FORM_SUBMITTED"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    APPROVED = "APPROVED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
