"""ORM model for the ``review_workflows`` table.

The table is created and maintained by Alembic migrations
(``alembic/versions/0001_initial.py``). A PostgreSQL trigger automatically
updates ``updated_at`` on every row modification.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, Index, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.constants.enums import ReviewStatus
from app.database import Base


class ReviewWorkflow(Base):
    """Persistent record for a single employee review workflow execution.

    One row is created when a review is started via ``POST /api/reviews/start``
    and is updated in-place as the Temporal workflow progresses through its
    lifecycle states.

    Attributes:
        id: UUID primary key; generated by PostgreSQL ``gen_random_uuid()``.
        workflow_id: Human-readable unique identifier used as the Temporal
            workflow ID (format: ``review-{employee_id}-{8-char hex}``).
        employee_id: Identifier of the employee under review.
        lead_id: Identifier of the lead responsible for approval.
        status: Current lifecycle state; one of :class:`~app.constants.enums.ReviewStatus`.
        form_data: JSONB payload submitted by the employee during self-review.
            ``None`` until the ``form_submitted`` signal is received.
        ai_summary: LLM-generated performance summary.
            ``None`` until the AI summary activity completes.
        rating: Lead's rating string (e.g. ``"exceeds_expectations"``).
            ``None`` until the ``lead_approved`` signal is received.
        created_at: Timestamp of row creation (timezone-aware).
        updated_at: Timestamp of last modification; maintained by a DB trigger.
    """

    __tablename__ = "review_workflows"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    workflow_id: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)
    employee_id: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    lead_id: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    status: Mapped[str] = mapped_column(
        String(50), nullable=False, default=ReviewStatus.INITIATED, index=True
    )
    form_data: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    ai_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    rating: Mapped[str | None] = mapped_column(String(50), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    __table_args__ = (
        Index("ix_review_workflows_created_at_desc", "created_at"),
    )
